---
- hosts: all
  become: yes
  tasks:
    - name: Update package cache
      block:
        - name: Update apt cache
          ansible.builtin.apt:
            update_cache: yes
            cache_valid_time: 3600
            force_apt_get: yes
          when: ansible_pkg_mgr == 'apt'

        - name: Update dnf cache
          ansible.builtin.dnf:
            update_cache: yes
          when: ansible_pkg_mgr == 'dnf'

        - name: Update dnf5 cache
          ansible.builtin.dnf5:
            update_cache: yes
          when: ansible_pkg_mgr == 'dnf5'

        - name: Update pacman cache
          community.general.pacman:
            update_cache: yes
          when: ansible_pkg_mgr == 'pacman'

        - name: Update zypper cache
          ansible.builtin.command: zypper --non-interactive refresh
          changed_when: false
          when: ansible_pkg_mgr == 'zypper'

    - name: Install required packages
      ansible.builtin.package:
        name:
          - screen
          - vim
        state: present

    - name: Create required directories
      ansible.builtin.file:
        path: /run/screen
        state: directory
        mode: '0777'

    - name: Ensure the 'user' account can run sudo commands without a password
      ansible.builtin.copy:
        dest: /etc/sudoers.d/user
        content: |
          user ALL=(ALL) NOPASSWD: ALL
        mode: '0440'
        owner: root
        group: root
