---
- hosts: all
  become: yes
  tasks:
    - name: Install kubectl bash completion
      ansible.builtin.shell: kubectl completion bash > /etc/bash_completion.d/kubectl
      args:
        creates: /etc/bash_completion.d/kubectl
